
img_size: 64
in_channels: 3
num_classes: 2
TOPT_CYCLE: 100  # To be tuned.

model:
    hidden_dims: [32, 64, 128, 256, 512]

train:
    lr: 0.005
    n_epochs: 20

data:
    name: "cifar10"
    train_batch_size: 64
    test_batch_size: 32
    download: False
    